#server:
#  port: 3344
#spring:
#  application:
#    name: springcloud-config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/fanjianhai/SpringCloudConfig.git


spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: springcloud-config-dev
---
spring:
  profiles: dev
  application:
    name: springcloud-config-dev